[package]
name = "server-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
rocket = { version = "0.5.1", features = ["json"] }

[dev-dependencies]
anyhow = "1"
